#!/usr/bin/env bash
# Generates tests/spec-coverage.md from /// Covers: doc comments
# across the workspace. Run via `just spec-coverage`. CI asserts the
# committed file matches the generated output.
#
# Convention per verification.md §22.2.
set -euo pipefail

OUT="tests/spec-coverage.md"
ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

cat > "$OUT" <<'EOF'
# Spec-coverage matrix

Generated by `just spec-coverage`. Do not hand-edit; CI fails on diff.

Mapping: each spec section to the tests that prove it. Tests carry
`/// Covers: <file>.md §X.Y` doc comments; this file aggregates them.

EOF

# Find every test file and grep `/// Covers:` lines.
grep -RIn --include='*.rs' '/// Covers:' \
    crates tests \
    2>/dev/null \
| awk '{
    # Parse "<file>:<line>:<content>" by anchoring on the first two colons.
    p1 = index($0, ":"); rest1 = substr($0, p1+1);
    p2 = index(rest1, ":"); content = substr(rest1, p2+1);
    file = substr($0, 1, p1-1);
    line = substr(rest1, 1, p2-1);
    # Strip everything up to and including "Covers:".
    sub(/.*Covers:[[:space:]]*/, "", content);
    # Strip trailing punctuation/whitespace.
    sub(/[.[:space:]]*$/, "", content);
    n = split(content, parts, /,[[:space:]]*/);
    for (i=1; i<=n; i++) {
        sec = parts[i]; sub(/[.[:space:]]*$/, "", sec);
        print sec "\t" file ":" line;
    }
}' \
| sort -k1,1 -k2,2 \
| awk -F'\t' '
    BEGIN { last="" }
    {
        if ($1 != last) {
            if (last != "") print "";
            print "## " $1;
            last = $1;
        }
        print "- " $2;
    }
' >> "$OUT"

echo "Wrote $OUT"
